ShopEnLigne/Models/BlackList.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace ShopEnLigne.Models
{
    public class BlackList
    {
        [Key]
        public int Id { get; set; }
        [ForeignKey("UserId")]
        public int UserId { get; set; }
        public virtual User User { get; set; }
    }
}

ShopEnLigne/Controllers/BlackListsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ShopEnLigne.Data;
using ShopEnLigne.Models;

namespace ShopEnLigne.Controllers
{
    public class BlackListsController : Controller
    {
        private readonly ShopEnLigneContext _context;

        public BlackListsController(ShopEnLigneContext context)
        {
            _context = context;
        }

        // GET: BlackLists
        public async Task<IActionResult> Index()
        {
            var shopEnLigneContext = _context.BlackList.Include(b => b.User);
            return View(await shopEnLigneContext.ToListAsync());
        }

        // GET: BlackLists/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blackList = await _context.BlackList
                .Include(b => b.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (blackList == null)
            {
                return NotFound();
            }

            return View(blackList);
        }

        // GET: BlackLists/Create
        public IActionResult Create()
        {
            ViewData["UserId"] = new SelectList(_context.User, "Id", "Username");
            return View();
        }

        // POST: BlackLists/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,UserId")] BlackList blackList)
        {
            if (!ModelState.IsValid)
            {
                _context.Add(blackList);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.User, "Id", "Id", blackList.UserId);
            return View(blackList);
        }

        // GET: BlackLists/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blackList = await _context.BlackList.FindAsync(id);
            if (blackList == null)
            {
                return NotFound();
            }
            ViewData["UserId"] = new SelectList(_context.User, "Id", "Username", blackList.UserId);
            return View(blackList);
        }

        // POST: BlackLists/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,UserId")] BlackList blackList)
        {
            if (id != blackList.Id)
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                try
                {
                    _context.Update(blackList);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BlackListExists(blackList.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.User, "Id", "Id", blackList.UserId);
            return View(blackList);
        }

        // GET: BlackLists/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blackList = await _context.BlackList
                .Include(b => b.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (blackList == null)
            {
                return NotFound();
            }

            return View(blackList);
        }

        // POST: BlackLists/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var blackList = await _context.BlackList.FindAsync(id);
            if (blackList != null)
            {
                _context.BlackList.Remove(blackList);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BlackListExists(int id)
        {
            return _context.BlackList.Any(e => e.Id == id);
        }
    }
}

ShopEnLigne/Controllers/FavoriteListsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ShopEnLigne.Data;
using ShopEnLigne.Models;

namespace ShopEnLigne.Controllers
{
    public class FavoriteListsController : Controller
    {
        private readonly ShopEnLigneContext _context;

        public FavoriteListsController(ShopEnLigneContext context)
        {
            _context = context;
        }

        // GET: FavoriteLists
        public async Task<IActionResult> Index()
        {
            var shopEnLigneContext = _context.FavoriteList.Include(f => f.User);
            return View(await shopEnLigneContext.ToListAsync());
        }

        // GET: FavoriteLists/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var favoriteList = await _context.FavoriteList
                .Include(f => f.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (favoriteList == null)
            {
                return NotFound();
            }

            return View(favoriteList);
        }

        // GET: FavoriteLists/Create
        public IActionResult Create()
        {
            ViewData["UserId"] = new SelectList(_context.User, "Id", "Username");
            return View();
        }

        // POST: FavoriteLists/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,UserId")] FavoriteList favoriteList)
        {
            if (!ModelState.IsValid)
            {
                _context.Add(favoriteList);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.User, "Id", "Id", favoriteList.UserId);
            return View(favoriteList);
        }

        // GET: FavoriteLists/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var favoriteList = await _context.FavoriteList.FindAsync(id);
            if (favoriteList == null)
            {
                return NotFound();
            }
            ViewData["UserId"] = new SelectList(_context.User, "Id", "Username", favoriteList.UserId);
            return View(favoriteList);
        }

        // POST: FavoriteLists/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,UserId")] FavoriteList favoriteList)
        {
            if (id != favoriteList.Id)
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                try
                {
                    _context.Update(favoriteList);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FavoriteListExists(favoriteList.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.User, "Id", "Id", favoriteList.UserId);
            return View(favoriteList);
        }

        // GET: FavoriteLists/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var favoriteList = await _context.FavoriteList
                .Include(f => f.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (favoriteList == null)
            {
                return NotFound();
            }

            return View(favoriteList);
        }

        // POST: FavoriteLists/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var favoriteList = await _context.FavoriteList.FindAsync(id);
            if (favoriteList != null)
            {
                _context.FavoriteList.Remove(favoriteList);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FavoriteListExists(int id)
        {
            return _context.FavoriteList.Any(e => e.Id == id);
        }
    }
}

ShopEnLigne/Controllers/HistoriquesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ShopEnLigne.Data;
using ShopEnLigne.Models;

namespace ShopEnLigne.Controllers
{
    public class HistoriquesController : Controller
    {
        private readonly ShopEnLigneContext _context;

        public HistoriquesController(ShopEnLigneContext context)
        {
            _context = context;
        }

        // GET: Historiques
        public async Task<IActionResult> Index()
        {
            var shopEnLigneContext = _context.Historique.Include(h => h.Bien).Include(h => h.User);
            return View(await shopEnLigneContext.ToListAsync());
        }

        // GET: Historiques/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var historique = await _context.Historique
                .Include(h => h.Bien)
                .Include(h => h.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (historique == null)
            {
                return NotFound();
            }

            return View(historique);
        }

        // GET: Historiques/Create
        public IActionResult Create()
        {
            ViewData["Bien"] = new SelectList(_context.Bien, "Id", "Titre");
            ViewData["User"] = new SelectList(_context.User, "Id", "Username");
            return View();
        }

        // POST: Historiques/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Date,UserId,BienId")] Historique historique)
        {
            if (!ModelState.IsValid)
            {
                _context.Add(historique);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["BienId"] = new SelectList(_context.Bien, "Id", "Id", historique.BienId);
            ViewData["UserId"] = new SelectList(_context.User, "Id", "Id", historique.UserId);
            return View(historique);
        }

        // GET: Historiques/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var historique = await _context.Historique.FindAsync(id);
            if (historique == null)
            {
                return NotFound();
            }
            ViewData["BienId"] = new SelectList(_context.Bien, "Id", "Id", historique.BienId);
            ViewData["UserId"] = new SelectList(_context.User, "Id", "Id", historique.UserId);
            return View(historique);
        }

        // POST: Historiques/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Date,UserId,BienId")] Historique historique)
        {
            if (id != historique.Id)
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                try
                {
                    _context.Update(historique);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HistoriqueExists(historique.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BienId"] = new SelectList(_context.Bien, "Id", "Id", historique.BienId);
            ViewData["UserId"] = new SelectList(_context.User, "Id", "Id", historique.UserId);
            return View(historique);
        }

        // GET: Historiques/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var historique = await _context.Historique
                .Include(h => h.Bien)
                .Include(h => h.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (historique == null)
            {
                return NotFound();
            }

            return View(historique);
        }

        // POST: Historiques/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var historique = await _context.Historique.FindAsync(id);
            if (historique != null)
            {
                _context.Historique.Remove(historique);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool HistoriqueExists(int id)
        {
            return _context.Historique.Any(e => e.Id == id);
        }
    }
}

ShopEnLigne/Views/BlackLists/Create.cshtml
@model ShopEnLigne.Models.BlackList

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>BlackList</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <select asp-for="UserId" class ="form-control" asp-items="ViewBag.UserId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ShopEnLigne/Views/BlackLists/Delete.cshtml
@model ShopEnLigne.Models.BlackList

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>BlackList</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ShopEnLigne/Views/BlackLists/Details.cshtml
@model ShopEnLigne.Models.BlackList

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>BlackList</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ShopEnLigne/Views/BlackLists/Edit.cshtml
@model ShopEnLigne.Models.BlackList

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>BlackList</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <select asp-for="UserId" class="form-control" asp-items="ViewBag.UserId"></select>
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ShopEnLigne/Views/BlackLists/Index.cshtml
@model IEnumerable<ShopEnLigne.Models.BlackList>

@{
    ViewData["Title"] = "Index";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/css/StyleDashboard.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ShopEnLigne.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <title>ECommerce-ShoppingCart | Korsat X Parmaga</title>

    <!-- BOX ICONS -->
    <link href='https://unpkg.com/boxicons@2.0.9/css/boxicons.min.css' rel='stylesheet'>
</head>
<body>
    <div class="container">
        <div class="menu-dashboard">
            <!-- TOP MENU -->
            <div class="top-menu">
                <div class="toggle">
                    <i class='bx bx-menu'></i>
                </div>
            </div>
            <!-- MENU -->
            <br />
            <br />
            <br />
            <div class="menu">
                <div class="enlace">
                    <i class="bx bx-log-out"></i>
                    <a asp-action="Index" asp-controller="Home" style="text-decoration:none;color:#E5D283"><span>Logout</span></a>
                </div>


                <div class="enlace">
                    <i class="bx bx-grid-alt"></i>
                    <a asp-action="Dashboard" asp-controller="Users" style="text-decoration:none;color:#E5D283"><span>Dashboard</span></a>
                </div>

                <div class="enlace">
                    <i class="bx bx-time"></i>
                    <a asp-action="Index" asp-controller="Historiques" style="text-decoration:none;color:#E5D283"><span>History</span></a>
                </div>

                <div class="enlace">
                    <i class="bx bx-file-blank"></i>
                    <a asp-action="Index" asp-controller="BlackLists" style="text-decoration:none;color:#E5D283"><span>BlackList</span></a>
                </div>

                <div class="enlace">
                    <i class="bx bx-heart"></i>
                    <a asp-action="Index" asp-controller="FavoriteLists" style="text-decoration:none;color:#E5D283"><span>FavList</span></a>
                </div>
            </div>
        </div>
        <div class="bodycontent">
            <h1 style="color:darkslategray;margin-left:500px;">Blacklist</h1>
            <table>
                <thead>
                    <tr style=" background-color: #4F709C;">
                        <th>
                            @Html.DisplayNameFor(model => model.User)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <p>
                    <a style="color:black;margin-left:300px" asp-action="Create">Create New</a>
                </p>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.User.Username)
                            </td>
                            <td class="btn-container">
                                @Html.ActionLink("Edit", "Edit", "BlackLists", new { id = item.Id }, new { @class = "btn btn-outline-secondary" })
                                @Html.ActionLink("Delete", "Delete", "BlackLists", new { id = item.Id }, new { @class = "btn btn-outline-danger" })
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
            <style>

                table {
                    width: 100%;
                    border-collapse: collapse;
                    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.4);
                    margin-left: 250px; /* Add margin for spacing */
                }

                th, td {
                    padding: 15px;
                    text-align: left;
                    border-bottom: 1px solid #ddd;
                    color: #5A5A5A;
                }

                td {
                    background-color: #F0F0F0;
                }

                th {
                    color: darkgray;
                    width: 200px;
                }
            </style>

        </div>
    </div>
    <script>
        const toggle = document.querySelector(".toggle")
        const menuDashboard = document.querySelector(".menu-dashboard")
        const iconoMenu = toggle.querySelector("i")
        const enlacesMenu = document.querySelectorAll(".enlace")

        toggle.addEventListener("click", () => {
            menuDashboard.classList.toggle("open")

            if (iconoMenu.classList.contains("bx-menu")) {
                iconoMenu.classList.replace("bx-menu", "bx-x")
            } else {
                iconoMenu.classList.replace("bx-x", "bx-menu")
            }
        })

        enlacesMenu.forEach(enlace => {
            enlace.addEventListener("click", () => {
                menuDashboard.classList.add("open")
                iconoMenu.classList.replace("bx-menu", "bx-x")
            })
        })

        document.getElementById('test').style.display = 'none';
        document.getElementById('test1').style.display = 'none';
    </script>
</body>
</html>