ShopEnLigne/Models/User.cs
using System.ComponentModel.DataAnnotations;

namespace ShopEnLigne.Models
{
    public class User
    {
        [Key]
        public int Id { get; set; }
        public string Email { get; set; }
        public string? Username { get; set; }
        public string? nom { get; set; }
        public string? prenom { get; set; }
        public string Password { get; set; }
        public string Photo { get; set; }
        // Propriétés spécifiques à la société
        public string? NomSociete { get; set; }
        public UserType? UserType { get; set; }

        public virtual ICollection<Bien> Bien { get; set; } = new List<Bien>();
        public virtual ICollection<Historique> Historique { get; set; } = new List<Historique>();
        public virtual ICollection<BlackList> BlackLists { get; set; } = new List<BlackList>();
        public virtual ICollection<FavoriteList> FavoriteLists { get; set; } = new List<FavoriteList>();
    }
}

ShopEnLigne/Models/UserType.cs
namespace ShopEnLigne.Models
{
    public enum UserType
    {
        Administrator,
        Proprietaire,
        Invite
    }
}

ShopEnLigne/Controllers/BiensController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ShopEnLigne.Data;
using ShopEnLigne.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using System.IO;


namespace ShopEnLigne.Controllers
{
    public class BiensController : Controller
    {
        private readonly ShopEnLigneContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public BiensController(ShopEnLigneContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Pay()
        {
            return View();
        }
        [HttpGet("BiensCount")]
        [Route("api/BiensCount")]
        public IActionResult GetBiensCountCount()
        {
            var count = _context.Bien.Count();
            return Ok(count);
        }

        public async Task<IActionResult> ProductsByCategory(int? categoryId)
        {
            if (categoryId == null)
            {
                return NotFound();
            }

            var category = await _context.Categorie.FindAsync(categoryId);

            if (category == null)
            {
                return NotFound();
            }

            var productsInCategory = await _context.Bien
                .Include(b => b.Categorie)
                .Include(b => b.User)
                .Where(b => b.CategorieId == categoryId)
                .ToListAsync();

            ViewData["CategoryName"] = category.Nom;

            return View("Index", productsInCategory);
        }

        public bool IsUserLoggedIn()
        {
            return HttpContext.User.Identity.IsAuthenticated;
        }

        // GET: Biens
        public async Task<IActionResult> Index()
        {
            var shopEnLigneContext = _context.Bien.Include(b => b.Categorie).Include(b => b.User);
            return View(await shopEnLigneContext.ToListAsync());
        }

        // GET: Biens/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bien = await _context.Bien
                .Include(b => b.Categorie)
                .Include(b => b.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (bien == null)
            {
                return NotFound();
            }

            return View(bien);
        }

        // GET: Biens/Create
        public IActionResult Create()
        {
            ViewData["CategorieId"] = new SelectList(_context.Categorie, "Id", "Nom");
            ViewData["UserId"] = new SelectList(_context.User, "Id", "Username");
            return View();
        }

        // POST: Biens/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Titre,Description,Photo,Prix,IsAvailable,UserId,CategorieId")] Bien bien, IFormFile photoFile)
        {
            if (!ModelState.IsValid)
            {
                try
                {
                    if (photoFile != null && photoFile.Length > 0)
                    {
                        // Save the image to the server (e.g., in wwwroot/images)
                        var uploads = Path.Combine(_webHostEnvironment.WebRootPath, "Images");
                        var uniqueFileName = Guid.NewGuid().ToString() + "_" + photoFile.FileName;
                        var filePath = Path.Combine(uploads, uniqueFileName);

                        using (var fileStream = new FileStream(filePath, FileMode.Create))
                        {
                            await photoFile.CopyToAsync(fileStream);
                        }

                        // Update the Photo property of the Bien model
                        bien.Photo = uniqueFileName;
                    }

                    _context.Add(bien);
                    await _context.SaveChangesAsync();
                    // Load the User navigation property
                    bien = _context.Bien.Include(b => b.User).Single(b => b.Id == bien.Id);
                    // Create a new Historique entry
                    var historique = new Historique
                    {
                        Date = DateTime.Now, // Set the date to the current date
                        UserId = bien.UserId, // Set the UserId to the UserId of the Bien
                        BienId = bien.Id // Set the BienId to the Id of the newly created Bien
                    };

                    _context.Add(historique);
                    await _context.SaveChangesAsync();

                    return RedirectToAction("Index","Users", new { username = bien.User.Username });
                }
                catch (DbUpdateException)
                {
                    // Log the error
                    ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
                }
            }
            ViewData["CategorieId"] = new SelectList(_context.Categorie, "Id", "Id", bien.CategorieId);
            ViewData["UserId"] = new SelectList(_context.User, "Id", "Id", bien.UserId);
            return View(bien);
        }

        // GET: Biens/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bien = await _context.Bien.FindAsync(id);
            if (bien == null)
            {
                return NotFound();
            }
            ViewData["CategorieId"] = new SelectList(_context.Categorie, "Id", "Nom", bien.CategorieId);
            ViewData["UserId"] = new SelectList(_context.User, "Id", "Username", bien.UserId);
            return View(bien);
        }

        // POST: Biens/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Titre,Description,Photo,Prix,IsAvailable,UserId,CategorieId")] Bien bien)
        {
            if (id != bien.Id)
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                try
                {
                    _context.Update(bien);
                    await _context.SaveChangesAsync();
                    bien = _context.Bien.Include(b => b.User).Single(b => b.Id == bien.Id);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BienExists(bien.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index", "Users", new { username = bien.User.Username });
            }
            ViewData["CategorieId"] = new SelectList(_context.Categorie, "Id", "Nom", bien.CategorieId);
            ViewData["UserId"] = new SelectList(_context.User, "Id", "Username", bien.UserId);
            return View(bien);
        }

        // GET: Biens/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bien = await _context.Bien
                .Include(b => b.Categorie)
                .Include(b => b.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (bien == null)
            {
                return NotFound();
            }

            return View(bien);
        }

        // POST: Biens/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var bien = await _context.Bien.Include(b => b.User).FirstOrDefaultAsync(b => b.Id == id);
            if (bien != null)
            {
                _context.Bien.Remove(bien);
                await _context.SaveChangesAsync();
            }

            // Redirect to the user's profile
            return RedirectToAction("Index", "Users", new { username = bien.User.Username });
        }

        private bool BienExists(int id)
        {
            return _context.Bien.Any(e => e.Id == id);
        }
    }
}

ShopEnLigne/Controllers/BlackListsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ShopEnLigne.Data;
using ShopEnLigne.Models;

namespace ShopEnLigne.Controllers
{
    public class BlackListsController : Controller
    {
        private readonly ShopEnLigneContext _context;

        public BlackListsController(ShopEnLigneContext context)
        {
            _context = context;
        }

        // GET: BlackLists
        public async Task<IActionResult> Index()
        {
            var shopEnLigneContext = _context.BlackList.Include(b => b.User);
            return View(await shopEnLigneContext.ToListAsync());
        }

        // GET: BlackLists/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blackList = await _context.BlackList
                .Include(b => b.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (blackList == null)
            {
                return NotFound();
            }

            return View(blackList);
        }

        // GET: BlackLists/Create
        public IActionResult Create()
        {
            ViewData["UserId"] = new SelectList(_context.User, "Id", "Username");
            return View();
        }

        // POST: BlackLists/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,UserId")] BlackList blackList)
        {
            if (!ModelState.IsValid)
            {
                _context.Add(blackList);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.User, "Id", "Id", blackList.UserId);
            return View(blackList);
        }

        // GET: BlackLists/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blackList = await _context.BlackList.FindAsync(id);
            if (blackList == null)
            {
                return NotFound();
            }
            ViewData["UserId"] = new SelectList(_context.User, "Id", "Username", blackList.UserId);
            return View(blackList);
        }

        // POST: BlackLists/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,UserId")] BlackList blackList)
        {
            if (id != blackList.Id)
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                try
                {
                    _context.Update(blackList);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BlackListExists(blackList.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.User, "Id", "Id", blackList.UserId);
            return View(blackList);
        }

        // GET: BlackLists/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blackList = await _context.BlackList
                .Include(b => b.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (blackList == null)
            {
                return NotFound();
            }

            return View(blackList);
        }

        // POST: BlackLists/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var blackList = await _context.BlackList.FindAsync(id);
            if (blackList != null)
            {
                _context.BlackList.Remove(blackList);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BlackListExists(int id)
        {
            return _context.BlackList.Any(e => e.Id == id);
        }
    }
}

ShopEnLigne/Views/Users/Dashboard.cshtml
@model ShopEnLigne.Models.Bien
@{
    ViewData["Title"] = "Dashboard";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/css/StyleDashboard.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ShopEnLigne.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <title>ECommerce-ShoppingCart | Korsat X Parmaga</title>

    <!-- BOX ICONS -->
    <link href='https://unpkg.com/boxicons@2.0.9/css/boxicons.min.css' rel='stylesheet'>
</head>
<body>
    <div class="container">
        <div class="menu-dashboard">
            <!-- TOP MENU -->
            <div class="top-menu">
                <div class="top-menu">
                    <div class="toggle">
                        <img src="~/Images/favicon.ico" alt="Your Logo" width="50" height="50" style="margin-left:-8px"/>
                    </div>
                </div>
            </div>
            <!-- MENU -->
            <br />
            <br />
            <br />
            <div class="menu">
                <div  class="enlace">
                    <i style="margin-left:7px" class="bx bx-log-out"></i>
                    <a asp-action="Index" asp-controller="Home" style="text-decoration:none;color:#E5D283"><span>Logout</span></a>
                </div>


                <div class="enlace">
                    <i style="margin-left:7px" class="bx bx-grid-alt"></i>
                    <a asp-action="Dashboard" asp-controller="Users" style="text-decoration:none;color:#E5D283"><span>Dashboard</span></a>
                </div>

                <div class="enlace">
                    <i style="margin-left:7px" class="bx bx-time"></i>
                    <a asp-action="Index" asp-controller="Historiques" style="text-decoration:none;color:#E5D283"><span>History</span></a>
                </div>

                <div class="enlace">
                    <i style="margin-left:7px" class="bx bx-file-blank"></i>
                    <a asp-action="Index" asp-controller="BlackLists" style="text-decoration:none;color:#E5D283"><span>BlackList</span></a>
                </div>

                <div class="enlace">
                    <i style="margin-left:7px" class="bx bx-heart"></i>
                    <a asp-action="Index" asp-controller="FavoriteLists" style="text-decoration:none;color:#E5D283"><span>FavList</span></a>
                </div>
            </div>
        </div>
        <div style="margin-left:120px" class="cardcover">
            <div class="card" id="cardSeller">
                <div class="title">
                    <span style="background-color:coral;">
                        <svg viewBox="0 0 448 512" xmlns="http://www.w3.org/2000/svg" height="20" fill="currentColor" width="20">
                            <path d="M224 256c70.7 0 128-57.31 128-128s-57.3-128-128-128C153.3 0 96 57.31 96 128S153.3 256 224 256zM274.7 304H173.3C77.61 304 0 381.6 0 477.3c0 19.14 15.52 34.67 34.66 34.67h378.7C432.5 512 448 496.5 448 477.3C448 381.6 370.4 304 274.7 304z"></path>
                        </svg>
                    </span>
                    <p class="title-text">
                        Users 
                    </p>
                </div>
                <div class="data">
                    <p id="userCount">
                        N Guest
                    </p>

                    <div class="range">
                        <div class="fill" style="background-color:coral;">
                        </div>
                    </div>
                </div>
            </div>

            <div class="card" id="cardUser">
                <div class="title">
                    <span style="background-color:lightseagreen;">
                        <svg viewBox="0 0 448 512" xmlns="http://www.w3.org/2000/svg" height="20" fill="currentColor" width="20">
                            <path d="M224 256c70.7 0 128-57.31 128-128s-57.3-128-128-128C153.3 0 96 57.31 96 128S153.3 256 224 256zM274.7 304H173.3C77.61 304 0 381.6 0 477.3c0 19.14 15.52 34.67 34.66 34.67h378.7C432.5 512 448 496.5 448 477.3C448 381.6 370.4 304 274.7 304z"></path>
                        </svg>
                    </span>
                    <p class="title-text">
                        Users
                    </p>

                </div>
                <div class="data">
                    <p id="sellerCount">
                        N Seller
                    </p>

                    <div class="range">
                        <div class="fill" style="background-color:lightseagreen;">
                        </div>
                    </div>
                </div>
            </div>
            <div class="card" id="cardItem">
                <div class="title">
                    <span>
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1792 1792" height="20" fill="currentColor" width="20">
                            <path d="M1362 1185q0 153-99.5 263.5t-258.5 136.5v175q0 14-9 23t-23 9h-135q-13 0-22.5-9.5t-9.5-22.5v-175q-66-9-127.5-31t-101.5-44.5-74-48-46.5-37.5-17.5-18q-17-21-2-41l103-135q7-10 23-12 15-2 24 9l2 2q113 99 243 125 37 8 74 8 81 0 142.5-43t61.5-122q0-28-15-53t-33.5-42-58.5-37.5-66-32-80-32.5q-39-16-61.5-25t-61.5-26.5-62.5-31-56.5-35.5-53.5-42.5-43.5-49-35.5-58-21-66.5-8.5-78q0-138 98-242t255-134v-180q0-13 9.5-22.5t22.5-9.5h135q14 0 23 9t9 23v176q57 6 110.5 23t87 33.5 63.5 37.5 39 29 15 14q17 18 5 38l-81 146q-8 15-23 16-14 3-27-7-3-3-14.5-12t-39-26.5-58.5-32-74.5-26-85.5-11.5q-95 0-155 43t-60 111q0 26 8.5 48t29.5 41.5 39.5 33 56 31 60.5 27 70 27.5q53 20 81 31.5t76 35 75.5 42.5 62 50 53 63.5 31.5 76.5 13 94z">
                            </path>
                        </svg>
                    </span>
                    <p class="title-text">
                        Stock
                    </p>

                </div>
                <div class="data">
                    <p id="itemCount">
                        N item
                    </p>

                    <div class="range">
                        <div class="fill">
                        </div>
                    </div>
                </div>
            </div>
            <div class="card" id="cardSalles">
                <div class="title">
                    <span>
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1792 1792" height="20" fill="currentColor" width="20">
                            <path d="M1362 1185q0 153-99.5 263.5t-258.5 136.5v175q0 14-9 23t-23 9h-135q-13 0-22.5-9.5t-9.5-22.5v-175q-66-9-127.5-31t-101.5-44.5-74-48-46.5-37.5-17.5-18q-17-21-2-41l103-135q7-10 23-12 15-2 24 9l2 2q113 99 243 125 37 8 74 8 81 0 142.5-43t61.5-122q0-28-15-53t-33.5-42-58.5-37.5-66-32-80-32.5q-39-16-61.5-25t-61.5-26.5-62.5-31-56.5-35.5-53.5-42.5-43.5-49-35.5-58-21-66.5-8.5-78q0-138 98-242t255-134v-180q0-13 9.5-22.5t22.5-9.5h135q14 0 23 9t9 23v176q57 6 110.5 23t87 33.5 63.5 37.5 39 29 15 14q17 18 5 38l-81 146q-8 15-23 16-14 3-27-7-3-3-14.5-12t-39-26.5-58.5-32-74.5-26-85.5-11.5q-95 0-155 43t-60 111q0 26 8.5 48t29.5 41.5 39.5 33 56 31 60.5 27 70 27.5q53 20 81 31.5t76 35 75.5 42.5 62 50 53 63.5 31.5 76.5 13 94z">
                            </path>
                        </svg>
                    </span>
                    <p class="title-text">
                        Sales
                    </p>

                </div>
                <div class="data">
                    <p id="itemCount">
                        17 item
                    </p>

                    <div class="range">
                        <div class="fill">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="chart-container">
            <canvas id="userBiensChart"></canvas>
        </div>
    </div>
    <script>
        fetch('/api/userbiens')
            .then(response => response.json())
            .then(data => {
                var ctx = document.getElementById('userBiensChart').getContext('2d');
                new Chart(ctx, {
                    type: 'bar',
                    data: {
                        labels: data.map(item => item.username),
                        datasets: [{
                            label: '# of Biens',
                            data: data.map(item => item.biensCount),
                            backgroundColor: 'rgba(75, 192, 192, 0.2)',
                            borderColor: 'rgba(75, 192, 192, 1)',
                            borderWidth: 1
                        }]
                    },
                    options: {
                        scales: {
                            y: {
                                beginAtZero: true
                            }
                        },
                        responsive: true, // make the chart responsive
                        maintainAspectRatio: false, // maintain aspect ratio while resizing
                    }
                });
            });
        fetch('/api/inviteUserCount')
            .then(response => response.json())
            .then(data => {
                document.getElementById('userCount').innerText = + data + ' Guests';
            });
        fetch('/api/ProprietaireUserCount')
            .then(response => response.json())
            .then(data => {
                document.getElementById('sellerCount').innerText = data + ' Sellers';
            });
        fetch('/api/BiensCount')
            .then(response => response.json())
            .then(data => {
                document.getElementById('itemCount').innerText = data + ' Items';
            });
    </script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script>
        const toggle = document.querySelector(".toggle")
        const menuDashboard = document.querySelector(".menu-dashboard")
        const iconoMenu = toggle.querySelector("i")
        const enlacesMenu = document.querySelectorAll(".enlace")

        toggle.addEventListener("click", () => {
            menuDashboard.classList.toggle("open")

            if (iconoMenu.classList.contains("bx-menu")) {
                iconoMenu.classList.replace("bx-menu", "bx-x")
            } else {
                iconoMenu.classList.replace("bx-x", "bx-menu")
            }
        })

        enlacesMenu.forEach(enlace => {
            enlace.addEventListener("click", () => {
                menuDashboard.classList.add("open")
                iconoMenu.classList.replace("bx-menu", "bx-x")
            })
        })
    </script>
</body>
</html>

ShopEnLigne/Views/Users/Index.cshtml
@model ShopEnLigne.Models.User
@{
    ViewData["Title"] = "Profil";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/css/Profilestyle.css">
    <link rel="stylesheet" href="~/css/styleBien.css">
    <link rel="stylesheet" href="~/css/site.css">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <title>@ViewData["Title"]</title>
</head>
<body>
    <section id="personal">
        <div class="profilePic" style="background-image: url('../Images/@Model.Photo')"></div>
    </section>
    
    <section id="infos">
        <p id="username">@Model.Username</p>
        <button style="height:50px;" class="settings" id="add" onclick="location.href='@Url.Action("Create", "Biens")'">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#213555" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="svg-icon">
                <line x1="12" y1="5" x2="12" y2="19"></line>
                <line x1="5" y1="12" x2="19" y2="12"></line>
            </svg>
            <span class="lable">Add item</span>
        </button>
        <a asp-action="Edit" asp-controller="Users" asp-route-id="@Model.Id" style="height:50px;text-decoration:none" class="settings" id="edit" type="submit">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" viewBox="0 0 20 20" height="20" fill="none" class="svg-icon"><g stroke-width="1.5" stroke-linecap="round" stroke="#213555"><circle r="2.5" cy="10" cx="10"></circle><path fill-rule="evenodd" d="m8.39079 2.80235c.53842-1.51424 2.67991-1.51424 3.21831-.00001.3392.95358 1.4284 1.40477 2.3425.97027 1.4514-.68995 2.9657.82427 2.2758 2.27575-.4345.91407.0166 2.00334.9702 2.34248 1.5143.53842 1.5143 2.67996 0 3.21836-.9536.3391-1.4047 1.4284-.9702 2.3425.6899 1.4514-.8244 2.9656-2.2758 2.2757-.9141-.4345-2.0033.0167-2.3425.9703-.5384 1.5142-2.67989 1.5142-3.21831 0-.33914-.9536-1.4284-1.4048-2.34247-.9703-1.45148.6899-2.96571-.8243-2.27575-2.2757.43449-.9141-.01669-2.0034-.97028-2.3425-1.51422-.5384-1.51422-2.67994.00001-3.21836.95358-.33914 1.40476-1.42841.97027-2.34248-.68996-1.45148.82427-2.9657 2.27575-2.27575.91407.4345 2.00333-.01669 2.34247-.97026z" clip-rule="evenodd"></path></g></svg>
            <span class="lable">Edit account</span>
        </a>
        <button style="height:50px;" class="settings" id="add" onclick="location.href='@Url.Action("Create", "OffreSpeciales")'">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#213555" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="svg-icon">
                <line x1="12" y1="5" x2="12" y2="19"></line>
                <line x1="5" y1="12" x2="19" y2="12"></line>
            </svg>
            <span class="lable">Add promotion</span>
        </button>
    </section>
    <section id="forSale">
        <div class="shop-content">
            @foreach (var bien in Model.Bien)
            {
               <!-- BOX 1 -->
            <div class="product-box">
                <img src="~/Images/@bien.Photo" alt="" class="product-img">
                <h2 class="product-title"> @bien.Titre </h2>
                <span class="product-price">$@bien.Prix</span>
                    <a asp-action="Edit" asp-controller="Biens" asp-route-id="@bien.Id">
                        <i class='bx bx-edit add-cart'></i>
                    </a>

            </div> 
            }
        </div>
    </section>
</body>
</html>